# Generated by Django 3.2.9 on 2022-01-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('jenis_buku', models.TextField()),
                ('penulis', models.TextField()),
                ('penerbit', models.TextField()),
                ('tahun_terbit', models.TextField()),
            ],
        ),
    ]
