# Generated by Django 3.2.9 on 2022-01-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20220120_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='tahun_terbit',
            field=models.IntegerField(),
        ),
    ]
